# typed: false
# frozen_string_literal: true

# This file is generated by the Sigilix release pipeline. DO NOT EDIT.
class Sigilix < Formula
  desc "The grounded AI coding agent for the terminal."
  homepage "https://sigilix.ai"
  version "1.17.13"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.13/sigilix-darwin-x64.zip"
      sha256 "830281ffdd416d61336937dbdec8208d30049ff36741a505f791d5e8c2a4b9dc"

      def install
        bin.install "sigilix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.13/sigilix-darwin-arm64.zip"
      sha256 "63a1854285c55a9f569e34be8c520a1ff0b46a8c4c7f3e2039dafe3a15d5c432"

      def install
        bin.install "sigilix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.13/sigilix-linux-x64.tar.gz"
      sha256 "4f0aa5bdc7f52be8dcf98ee8f601f31873d370518776746541adea1178b32f80"
      def install
        bin.install "sigilix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.13/sigilix-linux-arm64.tar.gz"
      sha256 "a80056404c9294e98f413a2cd6b534d0edcb5984931df9eb6f2a77faf610293e"
      def install
        bin.install "sigilix"
      end
    end
  end
end
