# typed: false
# frozen_string_literal: true

# This file is generated by the Sigilix release pipeline. DO NOT EDIT.
class Sigilix < Formula
  desc "The grounded AI coding agent for the terminal."
  homepage "https://sigilix.ai"
  version "1.17.9"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.9/sigilix-darwin-x64.zip"
      sha256 "9dd4558125412c711efd1fa7a7b22f8da73631b8d764f515d4b3838e9ec2d81f"

      def install
        bin.install "sigilix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.9/sigilix-darwin-arm64.zip"
      sha256 "4cb6750e56e33c1fb4f9480dbe8d6ddb9fd55dc36d73d5c146f46047a65c4847"

      def install
        bin.install "sigilix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.9/sigilix-linux-x64.tar.gz"
      sha256 "ff6591fb48a020d4b4f1b82e021ab4993a7323c5b838c57c8b07088bca8ab255"
      def install
        bin.install "sigilix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Sigilix/sigilix-cli/releases/download/v1.17.9/sigilix-linux-arm64.tar.gz"
      sha256 "cc1db82e7311682973dd0f8532ee9da4c0b7cc8ac3e385e7fa57afa5bb5d0acd"
      def install
        bin.install "sigilix"
      end
    end
  end
end
