# typed: false
# frozen_string_literal: true

# This file is generated by the Sigilix release pipeline. DO NOT EDIT.
class Sigilix < Formula
  desc "The grounded AI coding agent for the terminal."
  homepage "https://sigilix.ai"
  version "1.17.11"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sigilix/homebrew-tap/releases/download/v1.17.11/sigilix-darwin-x64.zip"
      sha256 "ce9a6e100a547cf7466d6b471c2d08da95435d014632f62e1cc7b6c0f5fd7932"

      def install
        bin.install "sigilix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sigilix/homebrew-tap/releases/download/v1.17.11/sigilix-darwin-arm64.zip"
      sha256 "83e31ae881ccec9c468b2bd71b13504043e6c4013a68d80925e65fba0600e93b"

      def install
        bin.install "sigilix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Sigilix/homebrew-tap/releases/download/v1.17.11/sigilix-linux-x64.tar.gz"
      sha256 "65fc0b3ab168bc75b00b98ebd6bad447930270130840f0878ec6e0e0f609dfc0"
      def install
        bin.install "sigilix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Sigilix/homebrew-tap/releases/download/v1.17.11/sigilix-linux-arm64.tar.gz"
      sha256 "3eee22edafa99dad34d9588615a482ab7e77551614f834719c24459de77e4de7"
      def install
        bin.install "sigilix"
      end
    end
  end
end
